name: CI

on:
  push:
    branches: [ main, feature-branch-demo ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Verify Installation
      run: |
        npm ls eslint
        npm ls eslint-plugin-react
        npm ls react
        npm ls react-dom
        
    - name: Run tests
      run: npm test

    - name: Lint code
      run: npm run lint
