apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-term-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: devops-project-container
        image: kalsiparth252/devops-project-image:latest
        ports:
        - containerPort: 80
