apiVersion: v1
kind: Service
metadata:
  name: yourdevops-term-projectapp-service
spec:
  type: NodePort
  selector:
    app: devops-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
